### ISSUE TITLE
Automatically Add Commit SHA and Message

### ISSUE THREAD

**Issue by lorenzoaiello** [ubient/laravel-vapor-action#17]
Hello,

It would be great if the commit hash and message were automatically included by default.

Ref Docs: https://docs.vapor.build/1.0/projects/deployments.html#git-commit-information

**Comment by benborgers** [comment]
I got the commit information working using this workflow, which is slightly modified from the readme (Docker example). The last line is all I modified, it uses the `github` variable that's already present when Actions are run. 

```
name: Deploy to Vapor

on:
  push:
    branches: [ master ]

jobs:
  vapor:
    name: Check out and deploy using Vapor
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Github Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Deploy to Production
      run: |
        docker run \
          --env VAPOR_API_TOKEN=${{ secrets.VAPOR_API_TOKEN }} \
          --volume $(pwd):/app \
          docker.pkg.github.com/ubient/laravel-vapor-action/laravel-vapor-action:latest \
          deploy production --commit="${{ github.event.commits[0].id }}" --message="${{ github.event.commits[0].message }}"
```
