### ISSUE TITLE
Make it possible to dynamically add extensions (via an Github actions argument/variable)

### ISSUE THREAD

**Issue by claudiodekker** [ubient/laravel-vapor-action#9]
Due to people needing certain “custom” extensions (such as GD in #8), it would be nice if we could define these at “runtime” (project specific)

Since you can’t really modify the Dockerfile itself at runtime, I‘d like to look into if we can read and install extensions (from a Github actions variable/argument) moments before executing the vapor CLI tool (in https://github.com/ubient/laravel-vapor-action/blob/master/vapor-entrypoint).

(Feel free to pick this up if you want, just let me know and I’ll assign you to the issue so others can see you’re working on it!)

**Comment by kurucu** [comment]
This would be a really helpful addition. No idea how to do this, but I'll read into it and see what I can offer.

**Comment by kurucu** [comment]
So, I've gone down a completely different route allowing me to customise the runner. I'm afraid it doesn't use laravel-vapor-action at all, but it works. Any thoughts?

```
name: Deploy to Production
on:
  push:
    branches:
      - master
jobs:
  laravel:
    name: Check out, build and deploy to Vapor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 7.4
          tools: pecl
          extensions: mbstring, dom, fileinfo, gd, bcmath, xml, tokenizer, zip, soap, intl, exif

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
        
      - name: Install Vapor CLI Globally
        run: composer global require laravel/vapor-cli
        
      - name: Deploy with Vapor
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
        run: /home/runner/.composer/vendor/bin/vapor deploy production
```
